#...............
# Parameters----
#...............

# Intervention year 
int_year <- 2026

# Disability weights

# We are going to compute the disability weights for every countryusing the GBD 2023 data. 
# Since the dw are not explicit, we compute it as the ratio of YLDs to prevalence for each cause and location.
# For overall modeling, the average frequency-weighted disability weight across the countries will be used, but we will also have country-specific dw for sensitivity analyses.

# dw <- as.data.table(read_excel("C:/Users/wrgar/OneDrive - UW/02Work/ResolveToSaveLives/GitHub/HTN-cost-model/DisabilityWeights4Countries.xlsx", 
#                  sheet = "Sheet1", range = "A2:G18"))

# Raw file: IHME-GBD_2023_DATA-52d32656-1

dt_burden_gbd <- fread(paste0(wd_raw,"GBD/","IHME-GBD_2023_DATA-52d32656-1.csv"))

# Keep only relevant columns
dt_burden_gbd <- dt_burden_gbd[measure_name %in% c("YLDs (Years Lived with Disability)","Prevalence"), .(location_name, cause_name, measure_name, val)]

# Reshape wide to have YLDs and Prevalence in separate columns
dt_burden_gbd[,measure_name := ifelse(measure_name == "YLDs (Years Lived with Disability)", "yld", "prevalence")]

dt_burden_gbd <- reshape(dt_burden_gbd, idvar = c("location_name", "cause_name"), timevar = "measure_name", direction = "wide")

# encode causes names
# Invert it (name -> code)
cause_map_inv <- setNames(names(cause_map), cause_map)

# Encode
dt_burden_gbd[, cause := cause_map_inv[cause_name]]

# compute dw
dt_burden_gbd[, dw := val.yld / val.prevalence]

dt_burden_gbd[,location:=location_name]

dw <- dt_burden_gbd[,c("location","cause","dw"),with=F]

# Rename certain Countries to match main file names

loc_fix <- c(
  "Bolivia (Plurinational State of)" = "Bolivia",
  "Côte d'Ivoire"                   = "Ivory Coast",
  "Taiwan"                          = "Taiwan (Province of China)",
  "United Republic of Tanzania"     = "Tanzania",
  "Türkiye"                         = "Turkey",
  "United States of America"        = "United States"
)

dw[
  location %in% names(loc_fix),
  location := loc_fix[location]
]

# Life expectancy

# The life expectancy data is from the UN World Population Prospects 2024, 
# which provides life expectancy by age for both sexes. We will use the medium variant projections for our analysis. The data is in the "WPP2024_MORT_F05_1_LIFE_EXPECTANC

# Web link: https://population.un.org/wpp/downloads?folder=Standard%20Projections&group=Mortality
# Life Expectancy at Exact Age x (ex) - Both Sexes (XLSX) WPP2024_MORT_F05_1_LIFE_EXPECTANCY_BY_AGE_BOTH_SEXES.xlsx

# The average number of remaining years of life expected by a hypothetical cohort of 
# individuals alive at age x who would be subject during the remaining of their lives 
# to the mortality rates of a given year. It is expressed as years.

lt <- as.data.table(read_excel(paste0(wd_raw,"WPP2024_MORT_F05_1_LIFE_EXPECTANCY_BY_AGE_BOTH_SEXES.xlsx"), 
                               sheet = "Medium variant", range = "A17:DH22967"))

setnames(lt,c("Region, subregion, country or area *","Notes","Location code","ISO3 Alpha-code","ISO2 Alpha-code","SDMX code**","Type","Parent code","Year"),
           c("location","Notes","Locationcode","ISO3","ISO2","SDMX","Type","Parencode","year"))

lt_interp <- melt(lt,id.vars = colnames(lt)[1:11],value.name = "le",variable.name = "age")

# Filter the data.table
lt_interp <- lt_interp[year >= 2025,c("location","age","year","le"),with = F]

lt_interp[,age := as.numeric(as.character(str_extract_all(age, "\\d+")))]

lt_interp[,le:=as.numeric(le)]

loc_fix_lt <- c(
  "Bolivia (Plurinational State of)" = "Bolivia",
  "Côte d'Ivoire"                   = "Ivory Coast",
  "China, Taiwan Province of China" = "Taiwan (Province of China)",
  "United Republic of Tanzania"     = "Tanzania",
  "Türkiye"                         = "Turkey",
  "United States of America"        = "United States",
  "Dem. People's Republic of Korea" = "Democratic People's Republic of Korea",
  "Micronesia (Fed. States of)"     = "Micronesia (Federated States of)",
  "State of Palestine"              = "Palestine"
)

lt_interp[
  location %in% names(loc_fix_lt),
  location := loc_fix_lt[location]
]

# Cleaning
rm(lt)

#...............................
# Lives saved ----
#...............................

# Generated by 06_run_scenarios_multiple.R
out_model_path <- paste0(wd_outp, "out_model/")
files <- list.files(path = out_model_path, pattern = "\\.rds$", full.names = TRUE)

if (length(files) == 0)
  stop(paste0("No .rds files found in: ", out_model_path,
              "\nRun 06_run_scenarios_multiple.R first."))

data.out <- rbindlist(
  lapply(files, function(f) { dt <- readRDS(f); setDT(dt); dt }),
  use.names = TRUE, fill = TRUE
)
data.out <- data.out[!is.na(location)]

data.out[intervention %in% c("baseline", "BAU", "b.a.u"),
         intervention := "b.a.u"]
data.out[intervention %in% c("bp_only", "antihypertensive",
                             "BP", "Antihypertensive therapy"),
         intervention := "HTN Control (General)"]
data.out[intervention %in% c("bp_diabetes_only", "antihypertensive_diabetes","BP_diabetes"),
         intervention := "HTN Control (Diabetes)"]
data.out[intervention %in% c("statins_only", "statins", "Statins"),
         intervention := "Improved Statin Uptake"]
data.out[intervention %in% c("all_interventions","BP + BP_diabetes + Statins"),
         intervention := "All Interventions"]

## keep only relevant scenarios

data.out <- data.out[intervention %in% c("b.a.u", "HTN Control (General)", "HTN Control (Diabetes)","Improved Statin Uptake","All Interventions")]

# # ---- Core: deaths delayed by intervention x year ----------------------------
# dt_base <- data.out[intervention == "b.a.u" & year >= 2025,
#                     .(baseline_deaths = sum(dead, na.rm = TRUE)),
#                     by = .(sex, year, location, cause, age)]
# 
# dt_nonbase <- data.out[intervention != "b.a.u" & year >= 2025,
#                        .(dead = sum(dead, na.rm = TRUE)),
#                        by = .(sex, year, location, cause, age, intervention)]
# 
# dt_lives <- merge(dt_nonbase, dt_base,
#                    by = c("sex", "year", "location", "cause", "age"),
#                    all.x = TRUE)
# dt_lives <- dt_lives[year>=int_year, deaths_delayed := baseline_deaths - dead]
# 
# # Assign 0 to NA deaths delayed (e.g., if no deaths in baseline or intervention)
# dt_lives[is.na(deaths_delayed), deaths_delayed := 0]

data.out[, c("eff_ir","eff_cf","htn_target_scenario"):=NULL]
dt_lives <- data.out[year>=int_year, ]

#...............
# DALYs----
#...............

dt <- merge(dt_lives,dw,by=c("location","cause"),all.x=T)

## how to deal with le<age??
dt <- merge(dt,lt_interp,by=c("location","age","year"),all.x = T)

dt[, yld := sick * dw]
dt[, yll := dead * le]
dt[, daly := yld + yll]

# save RDS to compute deaths delayed and burden of disease averted in report
# and executive slides
saveRDS(dt, paste0(wd_outp, "dt_output_dalys.rds"))

